// <auto-generated />
using CarListingApp.Api.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarListingApp.Api.Migrations
{
    [DbContext(typeof(CarListingDbContext))]
    [Migration("20230129021229_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("CarListingApp.Api.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Make = "Toyota",
                            Model = "Corolla",
                            Vin = "12345678901234567",
                            Year = "2019"
                        },
                        new
                        {
                            Id = 2,
                            Make = "Honda",
                            Model = "Civic",
                            Vin = "21345678901234568",
                            Year = "2018"
                        },
                        new
                        {
                            Id = 3,
                            Make = "Ford",
                            Model = "Ranger",
                            Vin = "31245678901234569",
                            Year = "2021"
                        },
                        new
                        {
                            Id = 4,
                            Make = "Chevrolet",
                            Model = "Camaro",
                            Vin = "42345678901234570",
                            Year = "2020"
                        },
                        new
                        {
                            Id = 5,
                            Make = "Dodge",
                            Model = "Charger",
                            Vin = "52341678901234571",
                            Year = "2019"
                        },
                        new
                        {
                            Id = 6,
                            Make = "Audi",
                            Model = "A5",
                            Vin = "62345178901234572",
                            Year = "2023"
                        },
                        new
                        {
                            Id = 7,
                            Make = "BMW",
                            Model = "M3",
                            Vin = "72345618901234573",
                            Year = "2022"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
